name: specgen
description: |-
  [specgen]
  A program generating pubspec.yaml automatically.
version: 2025.424.1215
homepage:
repository: https://github.com/dart-pkg/specgen
environment:
  sdk: ^3.7.2
aaa: this is aaa
bbb: this is bbb
executables:
  specgen: main
dependencies:
  dart_scan: ^2025.424.1203
  run: ^2025.424.1501
  sys: ^2025.424.1524
  yaml_edit: ^2.2.2
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.7
  test: ^1.25.15
