name: specgen
description: |-
  [specgen]
  A program generating pubspec.yaml automatically.
version: 2025.504.1212
homepage: 
repository: https://github.com/dart-pkg/specgen
environment:
  sdk: ^3.7.2
aaa: this is aaa
bbb: this is bbb
executables:
  specgen: main
dependencies:
  dart_scan: ^2025.504.1204
  std: ^2025.504.1143
  sys: ^2025.504.1149
  yaml_magic: ^1.0.6
dev_dependencies:
  test: ^1.25.15
  output: ^2025.502.1958
  lints: ^5.1.1
