name: specgen
description: |-
  [specgen]
  A program generating pubspec.yaml automatically.
version: 2025.423.1516
homepage: null
repository: https://github.com/dart-pkg/specgen
environment:
  sdk: ^3.7.2
aaa: this is aaa
dependencies:
  dart_scan: ^2025.421.2226
  embed_annotation: ^1.2.2
  sys: ^2025.422.2341
  text_serializer: ^2025.423.1447
dev_dependencies:
  build_runner: ^2.4.15
  embed: ^1.4.1
  lints: ^5.1.1
  output: ^1.0.7
  test: ^1.25.15
bbb: this is bbb
executables:
  specgen: main
