name: specgen
description: |-
  [specgen]
  A program generating pubspec.yaml automatically.
version: 2025.526.2344
homepage: 
repository: https://github.com/dart-pkg/specgen
environment:
  sdk: ^3.7.2
aaa: this is aaa
bbb: this is bbb
executables:
  specgen: main
dependencies:
  dart_scan: ^2025.526.2339
  std: ^2025.526.2333
  yaml_magic: ^1.0.6
dev_dependencies:
  test: ^1.26.2
  output: ^2025.502.1958
  lints: ^6.0.0
